@backend_todo_HostAddress = http://localhost:5126


POST {{backend_todo_HostAddress}}/api/todos
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": false,
  "categoryId": 2
}

###

